#!/usr/bin/env python3
"""Require every audited declaration and only Lean's standard axioms.

The general-ensemble theorem has explicit scientific hypotheses; the Haar
extension proves local reverse variance. Neither adds global axioms.
In particular, sorryAx and any user-defined axiom fail this check.
"""

import re
import sys
from pathlib import Path


EXPECTED = {
    "Fluctuations.log_endpointBinomialMass_lower",
    "Fluctuations.endpointBinomialMass_lower",
    "Fluctuations.endpointBinomialMass_diffusive_lower",
    "Fluctuations.brickworkSchedule_initial_sign_mean",
    "Fluctuations.brickworkEndpointOTOC_haar_mean",
    "Fluctuations.brickworkEndpointOTOC_haar_mean_images",
    "Fluctuations.brickworkEndpointOTOC_haar_mean_oneCell",
    "Fluctuations.brickworkEndpointOTOC_haar_mean_lightcone",
    "Fluctuations.brickworkEndpointOTOC_fixed_markov",
    "Fluctuations.brickworkEndpointOTOC_haar_markov",
    "Fluctuations.brickworkEndpointOTOC_conditional_sub_mean",
    "Fluctuations.brickworkEndpointOTOC_conditional_mean",
    "Fluctuations.brickworkEndpointOTOC_gate_variance",
    "Fluctuations.brickworkEvenRemainder_adjacent",
    "Fluctuations.brickworkEvenRemainder_misses",
    "Fluctuations.brickworkEvenPrefix_misses",
    "Fluctuations.coordinateSplit_measurePreserving",
    "Fluctuations.coordinateAverage_eq_integral_update",
    "Fluctuations.coordinateAverage_condExp",
    "Fluctuations.sum_coordinateAverage_variance_le",
    "Fluctuations.endpointEye_card_lower",
    "Fluctuations.endpointEye_card_upper",
    "Fluctuations.endpointEye_segmentBounds",
    "Fluctuations.endpointFrontConstant_pos",
    "Fluctuations.EndpointSegmentBounds.binomial_lower",
    "Fluctuations.EndpointSegmentBounds.front_lower",
    "Fluctuations.EndpointSegmentBounds.profile_lower",
    "Fluctuations.endpointPastFactor_lower_of_segment",
    "Fluctuations.endpointFutureFactor_lower_of_segment",
    "Fluctuations.endpointEye_factors_lower",
    "Fluctuations.endpointKilled_pow_images",
    "Fluctuations.pauliPairEvolution_selfAdjoint",
    "Fluctuations.pauliEndpointIndicator_haar_pair",
    "Fluctuations.pauliEndpointMass_haar_pair",
    "Fluctuations.pauliEndpointMass_layer_congr",
    "Fluctuations.pauliEndpointMass_shock",
    "Fluctuations.pauliEndpointMass_shockProjection",
    "Fluctuations.pauliEndpointMass_layer_shockProjection",
    "Fluctuations.pauliEndpointMass_odd",
    "Fluctuations.brickworkEndpointCellMass_odd",
    "Fluctuations.pauliEndpointMass_iterate_odd",
    "Fluctuations.brickworkEndpointCellMass_iterate_odd",
    "Fluctuations.endpointKilled_apply",
    "Fluctuations.endpointGradient_intertwines",
    "Fluctuations.endpointDifference_intertwines",
    "Fluctuations.endpointGradient_intertwines_pow",
    "Fluctuations.endpointDifference_intertwines_pow",
    "Fluctuations.endpointMarkov_apply",
    "Fluctuations.endpointMarkov_nonneg",
    "Fluctuations.endpointMarkov_column_sum",
    "Fluctuations.endpointPastFactor_eq_killed",
    "Fluctuations.endpointFutureFactor_eq_killed",
    "Fluctuations.endpointMarkov_last_succ",
    "Fluctuations.endpointMarkov_last_sum",
    "Fluctuations.endpointMarkov_last_images",
    "Fluctuations.endpointChainMean_images",
    "Fluctuations.endpointChainMean_lightcone",
    "Fluctuations.endpointMarkov_zero",
    "Fluctuations.endpointEvenMean_oneCell",
    "Fluctuations.endpointEvenMean_images",
    "Fluctuations.pauliEndpointMass_layer_difference",
    "Fluctuations.pauliEndpointMass_layer_twoSite_difference",
    "Fluctuations.endpointPhysicalEyeLabel_injective",
    "Fluctuations.endpointPhysicalEye_image",
    "Fluctuations.endpointPhysicalEye_card_bounds",
    "Fluctuations.endpointPhysicalEye_interior",
    "Fluctuations.endpointKilled_pow_ballot",
    "Fluctuations.endpointFutureFactor_ballot",
    "Fluctuations.endpointPastFactor_ballot",
    "Fluctuations.endpointPastFactor_frontProfile",
    "Fluctuations.endpointFutureFactor_frontProfile",
    "Fluctuations.endpointInfluenceConstant_pos",
    "Fluctuations.endpoint_affine_influence_lower",
    "Fluctuations.endpointVariance_of_conditional_formula",
    "Fluctuations.sum_variance_condExp_le",
    "Fluctuations.sum_complexVariance_condExp_le",
    "Fluctuations.pi_sum_complexVariance_condExp_le",
    "Fluctuations.gate_affine_variance",
    "Fluctuations.pi_variance_ge_sum_gate_influences",
    "Fluctuations.pi_variance_ge_card_mul",
    "Fluctuations.pi_variance_ge_inv_sqrt",
    "Fluctuations.globalHaarCovariance_equivariant",
    "Fluctuations.globalHaarCovariance_traceless",
    "Fluctuations.globalHaarConjugate_trace_product",
    "Fluctuations.globalHaarTraceCoefficient_product",
    "Fluctuations.globalHaarTraceCoefficient_norm_sq",
    "Fluctuations.globalHaarTraceCoefficient_input_product",
    "Fluctuations.globalHaarCrossCovariance_equivariant",
    "Fluctuations.globalHaarCrossCovariance_traceless",
    "Fluctuations.globalHaarConjugate_mixed_trace_product",
    "Fluctuations.globalHaarTraceCoefficient_mixed_product",
    "Fluctuations.localPauliB_eq_one_sub_quarter_A",
    "Fluctuations.otoc1_endpoint_gate_influence",
    "Fluctuations.otoc1_endpoint_variance_lower",
    "Fluctuations.otoc1_many_influential_gates",
    "Fluctuations.pauliMatrix_hermitian",
    "Fluctuations.pauliMatrix_involution",
    "Fluctuations.pauliMatrix_trace",
    "Fluctuations.pauliMatrix_trace_mul",
    "Fluctuations.twoQubitPauli_hermitian",
    "Fluctuations.twoQubitPauli_involution",
    "Fluctuations.twoQubitPauli_trace",
    "Fluctuations.twoQubitPauli_trace_mul",
    "Fluctuations.twoQubitPauli_reconstruction",
    "Fluctuations.twoQubitPauli_expansion",
    "Fluctuations.twoQubitPauli_trace_mul_parseval",
    "Fluctuations.pauliLayerEvolution_shock_hit",
    "Fluctuations.brickworkRank_injective",
    "Fluctuations.brickworkOdd_shock",
    "Fluctuations.brickworkEven_shock_hit",
    "Fluctuations.brickworkEven_shock_first",
    "Fluctuations.brickworkEven_shock_last",
    "Fluctuations.brickworkPeriod_linear",
    "Fluctuations.brickworkPeriod_cellShock",
    "Fluctuations.brickworkPeriod_iterate_cellShock",
    "Fluctuations.pauliLayerEvolution_ofFn",
    "Fluctuations.brickworkCircuitBond_distinct",
    "Fluctuations.brickworkCircuitBond_odd",
    "Fluctuations.brickworkCircuitBond_even",
    "Fluctuations.brickworkEvenGateIndex_injective",
    "Fluctuations.brickworkEvenGate_later_cover",
    "Fluctuations.brickworkCircuit_markov",
    "Fluctuations.brickworkInitialZ_prefix",
    "Fluctuations.brickworkFrozenMarkov_sign_gap",
    "Fluctuations.brickworkInitialZ_odd_layer",
    "Fluctuations.brickworkGateSchedule_take_even",
    "Fluctuations.brickworkGateSchedule_drop_even",
    "Fluctuations.brickworkGateSchedule_even_decomposition",
    "Fluctuations.pauliCircuit_conjugate_expansion",
    "Fluctuations.pauliCircuit_otoc_quadratic",
    "Fluctuations.pauliCircuit_haar_covariance",
    "Fluctuations.pauliCircuit_haar_otoc_markov",
    "Fluctuations.pauliCircuit_fixed_gate_otoc",
    "Fluctuations.pauliString_siteZ_square",
    "Fluctuations.pauliOTOCWeight_siteZ_diagonal",
    "Fluctuations.pauliCircuit_haar_endpoint_otoc",
    "Fluctuations.pauliPairEvolution_product_pairing",
    "Fluctuations.pauliEndpointMass_pair_front",
    "Fluctuations.pauliEndpointMass_fixed_left",
    "Fluctuations.pauliEndpointMass_fixed_right",
    "Fluctuations.pauliShock_fixed_away",
    "Fluctuations.pauliEndpointMass_fixed_delta",
    "Fluctuations.pauliEndpointMass_fixed_mixture_delta",
    "Fluctuations.brickworkFixedPair_cell_delta",
    "Fluctuations.brickworkFuture_cell_delta",
    "Fluctuations.brickworkFixedPair_future_gap",
    "Fluctuations.brickworkFixedPair_future_site_gap",
    "Fluctuations.brickworkFixedMatching_future_sign_gap",
    "Fluctuations.pauliPairTransfer_haar_mixed",
    "Fluctuations.pauliPairTransfer_haar_row_covariance",
    "Fluctuations.pauliFrozenCovariance_diagonal",
    "Fluctuations.pauliFrozenCovariance_site_zero",
    "Fluctuations.pauliFrozenCovariance_eq_diagonal",
    "Fluctuations.pauliCircuit_fixed_gate_otoc_markov",
    "Fluctuations.pauliCircuit_fixed_gate_endpoint_otoc",
    "Fluctuations.pauliPairSquaredTransfer_mul",
    "Fluctuations.pauliCircuit_otoc_continuous",
    "Fluctuations.pauliFrozenMarkov_split",
    "Fluctuations.brickworkFrozenMarkov_split",
    "Fluctuations.pauliPairEvolution_pairing",
    "Fluctuations.pauliPairEvolution_totalMass_of_column_sum",
    "Fluctuations.pauliFixedPair_totalMass",
    "Fluctuations.twoQubitPauliCoefficient_haar_product",
    "Fluctuations.twoQubitPauliCoefficient_haar_norm_sq",
    "Fluctuations.twoQubitPauliCoefficient_haar_mean",
    "Fluctuations.twoQubitPauliCoefficient_haar_covariance",
    "Fluctuations.twoQubitPauliTransfer_haar_covariance",
    "Fluctuations.twoQubitPauliTransfer_column_inner",
    "Fluctuations.twoQubitPauliTransfer_column_sq",
    "Fluctuations.twoQubitPauliTransfer_row_sq",
    "Fluctuations.localPauliA_haar_mean",
    "Fluctuations.localPauliA_variance_pos",
    "Fluctuations.pauliPairEvolution_commute",
    "Fluctuations.pauliPairEvolution_commute_layer",
    "Fluctuations.pauliFixedPair_first",
    "Fluctuations.pauliShock_haar_pair",
    "Fluctuations.pauliPairKernel_mul",
    "Fluctuations.pauliStringMatrix_pair_split",
    "Fluctuations.pauliPairEmbedding_conjugate_pauli",
    "Fluctuations.pauliPairTransfer_sum_smul",
    "Fluctuations.pauliPairEmbedding_conjugate_pauli_transfer",
    "Fluctuations.pauliPairEmbedding_conjugate_expansion",
    "Fluctuations.pauliPairTransfer_continuous",
    "Fluctuations.pauliPairTransfer_haar_column_covariance",
    "Fluctuations.pauliLayerEvolution_untouched_expectation",
    "Fluctuations.brickworkEven_sign",
    "Fluctuations.brickworkIterateOddEven_sign",
    "Fluctuations.integral_independent_matrix_update",
    "Fluctuations.integral_randomLinearEvolution_mul",
    "Fluctuations.fullSecondMomentEvolution_diagonal",
    "Fluctuations.integral_randomLinearEvolution_diagonal",
    "Fluctuations.coordinateAverage_randomLinearEvolution_mul",
    "Fluctuations.integral_randomLinearEvolution_quadratic",
    "Fluctuations.coordinateAverage_randomLinearEvolution_quadratic",
    "Fluctuations.pauliEndpointIndicator_eq_ite",
    "Fluctuations.pauliPairEvolution_totalMass",
    "Fluctuations.brickworkLastPair_sign",
    "Fluctuations.brickworkOdd_sign",
    "Fluctuations.brickworkIterateOdd_sign",

    "Fluctuations.globalHaarOTOCMean_norm_le_one",
    "Fluctuations.globalHaarOTOCMean_norm_le_all_dimensions",
    "Fluctuations.globalHaarOTOCMean_norm_le_quarter_all_dimensions",

    "Fluctuations.globalHaarOTOCMean_eq_weingarten",
    "Fluctuations.globalHaarOTOCMean_norm_le",
    "Fluctuations.globalHaarOTOCMean_norm_le_quarter",
    "Fluctuations.spatialHaarCircuit_allOrders_of_globalHaar_control",

    "Fluctuations.unitaryConjugationEquivariant_classification",
    "Fluctuations.globalHaarOTOCMean_one_exact",
    "Fluctuations.globalHaarOTOCMean_one_norm_le_quarter",
    "Fluctuations.globalHaarOTOCMatrixMean_scalar_of_traceless_involution",
    "Fluctuations.globalHaarOTOCMean_state_independent_of_traceless_involution",
    "Fluctuations.globalHaarOTOCMean_traceless_involution_eq_normalized_trace",
    "Fluctuations.tensorPower_commutant_eq_permutation_sum",
    "Fluctuations.tensorPower_commutant_mem_span",
    "Fluctuations.matrixPolynomialEval_zero_of_unitary",
    "Fluctuations.tensorPower_commute_all_of_unitary",
    "Fluctuations.tensorPower_unitary_commutant_eq_permutation_sum",
    "Fluctuations.tensorPower_unitary_commutant_mem_span",
    "Fluctuations.globalHaarRepresentationMean_commute",
    "Fluctuations.globalHaarRepresentationMean_trace_pairing",
    "Fluctuations.globalHaarTensorMean_eq_permutation_sum",
    "Fluctuations.globalHaarTensorMean_mem_span",
    "Fluctuations.matrix_expansion_of_gram",
    "Fluctuations.tensorPositionPermutation_gram",
    "Fluctuations.tensorPowerMatrix_diagonal_trace_permutation",
    "Fluctuations.tensorPowerMatrix_traceless_involution_trace_permutation",
    "Fluctuations.globalHaarTensorMean_weingarten",
    "Fluctuations.trace_power_eq_tensor_cycle",
    "Fluctuations.globalHaarOTOCMean_maximallyMixed_eq_tensor",
    "Fluctuations.qubit_globalHaarOTOCMean_one_norm_le_quarter",
    "Fluctuations.spatialHaarCircuit_firstOrder_of_globalHaar_control",

    "Fluctuations.complex_total_variance",
    "Fluctuations.norm_mean_sq_le_secondMoment",
    "Fluctuations.slope_to_variance",
    "Fluctuations.forward_persistence",
    "Fluctuations.exists_large_increment",
    "Fluctuations.transition_window",
    "Fluctuations.theorem_VI_14",
    "Fluctuations.theorem_VI_14_interval",
    "Fluctuations.theorem_VI_14_family",
    "Fluctuations.finiteDimensional_reverseVariance",
    "Fluctuations.su4Haar_independent",
    "Fluctuations.matrixBlockOTOC_mem",
    "Fluctuations.matrixBlockOTOC_apply",
    "Fluctuations.qubitEmbedding",
    "Fluctuations.qubitEmbedding_injective",
    "Fluctuations.starAlgHom_su4_mem_unitary",
    "Fluctuations.product_condExp",
    "Fluctuations.product_localReverseVariance",
    "Fluctuations.haarLocalConstant_pos",
    "Fluctuations.haarLocalOTOC_reverseVariance_identity",
    "Fluctuations.haarLocalOTOC_conditional_reverseVariance",
    "Fluctuations.history_transition_window",
    "Fluctuations.history_theorem_VI_14",
    "Fluctuations.haarCircuit_theorem_VI_14",
    "Fluctuations.theorem_VI_14_of_step_bounds",
    "Fluctuations.ordered_product_inactive_mul_active",
    "Fluctuations.haarBlockMatrix_mem_unitary",
    "Fluctuations.haarBlockMatrix_inactive_conjugation",
    "Fluctuations.matrix_conjugate_layer_eq_active",
    "Fluctuations.embedded_su4_layer_eq_active",
    "Fluctuations.disjoint_tensor_factors_commute",
    "Fluctuations.preLightCone_otoc_eq_one",
    "Fluctuations.integral_preLightCone_otoc_eq_one",
    "Fluctuations.mean_gap_of_error_budget",
    "Fluctuations.mean_gap_one_half",
    "Fluctuations.activeHaarCircuitMatrix_mem_unitary",
    "Fluctuations.activeHaarCircuitOTOC_section",
    "Fluctuations.activeHaarCircuit_localReverseVariance",
    "Fluctuations.activeHaarCircuit_step_bounds",
    "Fluctuations.activeHaarCircuit_early_mean",
    "Fluctuations.activeHaarCircuit_theorem_VI_14",
    "Fluctuations.activeHaarCircuit_theorem_of_moment_control",
    "Fluctuations.tensorMatrix_mul",
    "Fluctuations.Supported.commute",
    "Fluctuations.supported_patchMatrix",
    "Fluctuations.supported_patchEmbedding",
    "Fluctuations.patchEmbedding_injective",
    "Fluctuations.supported_twoQubitPatchEmbedding",
    "Fluctuations.twoQubitPatchEmbedding_mem_unitary",
    "Fluctuations.LayerArchitecture.card_active_le",
    "Fluctuations.LayerArchitecture.conjugate_eq_active",
    "Fluctuations.LayerArchitecture.supported_conjugate",
    "Fluctuations.supported_spatialCircuit",
    "Fluctuations.spatialCircuit_commute_of_disjoint",
    "Fluctuations.card_backwardCone_le",
    "Fluctuations.backwardActiveGateCount_le",
    "Fluctuations.HaarSpatialArchitecture.active_count_le",
    "Fluctuations.HaarSpatialArchitecture.card_lightCone_le",
    "Fluctuations.HaarSpatialArchitecture.circuit_supported",
    "Fluctuations.HaarSpatialArchitecture.early_commute",
    "Fluctuations.HaarSpatialArchitecture.inactive_commute",
    "Fluctuations.HaarSpatialArchitecture.early_mean",
    "Fluctuations.haar_subspace_reverseVariance",
    "Fluctuations.haarLocalOTOC_balanced_mem",
    "Fluctuations.balancedSU4_polynomial_translate_mem",
    "Fluctuations.balancedSU4_polynomial_finrank_le",
    "Fluctuations.explicitHaarConstant_pos",
    "Fluctuations.haarLocalOTOC_explicit_reverseVariance_identity",
    "Fluctuations.haarLocalOTOC_explicit_conditional_reverseVariance",
    "Fluctuations.activeHaarCircuit_explicit_step_bounds",
    "Fluctuations.activeHaarCircuit_explicit_variance_window",
    "Fluctuations.activeHaarCircuit_explicit_theorem_of_moment_control",
    "Fluctuations.explicitHaarWindowConstant_antitone",
    "Fluctuations.globalHaarOTOCMean_eq_trace_matrixMean",
    "Fluctuations.globalHaarOTOCMatrixMean_conjugation",
    "Fluctuations.globalHaarOTOCMatrixMean_commute",
    "Fluctuations.spatialHaarCircuit_variance_window",
    "Fluctuations.spatialHaarCircuit_of_globalHaar_control",
    "Fluctuations.globalHaarOTOCMatrixMean_conjugateProbe",
    "Fluctuations.globalHaarOTOCMatrixMean_conjugateButterfly",
    "Fluctuations.globalMaximallyMixedState_trace",
    "Fluctuations.globalHaarOTOCMean_balancedZ_state_independent",
    "Fluctuations.globalHaarOTOCMean_conjugateBalancedZ_state_independent",
    "Fluctuations.globalHaarOTOCMean_balancedZ_eq_normalized_trace",
    "Fluctuations.maximal_cycles_weingarten_argument_ne_one",
    "Fluctuations.weingartenOTOCSum_norm_le_factorial",
    "Fluctuations.norm_le_of_weingartenHaarIdentity",
    "Fluctuations.quarter_bound_of_weingartenHaarIdentity",
    "Fluctuations.globalHaarTwirl_one",
    "Fluctuations.globalHaarTwirl_trace",
    "Fluctuations.globalHaarTwirl_equivariant",
    "Fluctuations.globalHaarTwirl_superTrace",
    "Fluctuations.globalHaarOTOCMatrixMean_one_eq_twirl",
    "Fluctuations.normalizedPermutationGram_isUnit",
    "Fluctuations.normalizedPermutationGram_inverse_bounds",
    "Fluctuations.gramWeingarten_inverse_identity",
    "Fluctuations.gramWeingartenCoefficient_bounds",
    "Fluctuations.gramWeingartenOTOCSum_norm_le",
    "Fluctuations.norm_le_of_gramWeingartenHaarIdentity",
    "Fluctuations.quarter_bound_of_gramWeingartenHaarIdentity",
}
ALLOWED_AXIOMS = {"propext", "Classical.choice", "Quot.sound"}
REPORT = re.compile(
    r"^'([^']+)' (?:depends on axioms:\s*\[([^\]]*)\]"
    r"|does not depend on any axioms)\s*$",
    re.MULTILINE,
)


def main() -> int:
    if len(sys.argv) != 2:
        print("Usage: check-axioms.py LEAN_AUDIT_LOG", file=sys.stderr)
        return 2
    reports = REPORT.findall(Path(sys.argv[1]).read_text(encoding="utf-8"))
    seen = set()
    errors = []
    for name, raw_axioms in reports:
        if name in seen:
            errors.append(f"Duplicate audit entry: {name}")
        seen.add(name)
        axioms = {axiom.strip() for axiom in raw_axioms.split(",") if axiom.strip()}
        forbidden = axioms - ALLOWED_AXIOMS
        if forbidden:
            errors.append(f"{name} uses forbidden axioms: {', '.join(sorted(forbidden))}")
    for name in sorted(EXPECTED - seen):
        errors.append(f"Missing audit entry: {name}")
    for name in sorted(seen - EXPECTED):
        errors.append(f"Unexpected audit entry: {name}")
    if errors:
        print("Axiom audit failed:\n" + "\n".join(errors), file=sys.stderr)
        return 1
    print(
        f"Axiom audit passed for all {len(EXPECTED)} declarations: "
        "only propext, Classical.choice, and Quot.sound are allowed."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
